apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-{{ env "environment" }}
spec:
  serviceName: {{ .Chart.Name }}-{{ env "environment" }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ env "environment" }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ env "environment" }}
    spec:
      containers:
      - name: nginx
        {{ tuple (printf "%s-%s" .Chart.Name "nginx") . | werf_container_image }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
          - name: config-volume
            subPath: nginx.conf
            mountPath: /etc/nginx/nginx.conf
          - name: data-store
            mountPath: /var/www
            subPath: {{ .Chart.Name }}-www
      - name: php-fpm
        {{ tuple (printf "%s-%s" .Chart.Name "php-fpm") . | werf_container_image }}
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - "/root/joborgame/container-php-fpm-post-start.bash"
        env:
        - name: SSH_AUTH_SOCK
          value: /ssh-agent
        - name: ENVIRONMENT
          value: {{ env "environment" }}
        - name: HOME_USER_NAME
          value: {{ env "HOME_USER_NAME" }}
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        volumeMounts:
          - name: ssh-agent-sock
            mountPath: /ssh-agent
          - name: data-store
            mountPath: /var/www
            subPath: {{ .Chart.Name }}-www
      - name: mongodb
        {{ tuple (printf "%s-%s" .Chart.Name "mongodb") . | werf_container_image }}
        ports:
        - containerPort: 27017
          name: mongod
          protocol: TCP
        volumeMounts:
        - name: data-store
          mountPath: /data/db
          subPath: {{ .Chart.Name }}-mongodb
      - name: magic
        {{ tuple (printf "%s-%s" .Chart.Name "magic") . | werf_container_image }}
        env:
        - name: SSH_AUTH_SOCK
          value: /ssh-agent
        - name: ENVIRONMENT
          value: {{ env "environment" }}
        - name: HOME_USER_NAME
          value: {{ env "HOME_USER_NAME" }}
        ports:
        - containerPort: 8005
          name: http
          protocol: TCP
          hostPort: 8005
        volumeMounts:
          - name: ssh-agent-sock
            mountPath: /ssh-agent
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Chart.Name }}-config-files
      - name: data-store
        persistentVolumeClaim:
          claimName: nfs-pvc-{{ .Chart.Name }}-{{ env "environment" }}
      - name: ssh-agent-sock
        hostPath:
          path: /ssh-agent
          type: Socket
